language: php

services:
    - mysql

php:
    - 7.2
    - 7.3

before_script:
    - phpenv config-rm xdebug.ini || true
    - mysql -e "create database test;"
    - composer install
    - php Tests/Fixtures/bin/console --env=test doctrine:schema:create
    - php Tests/Fixtures/bin/console --env=test doctrine:schema:update --force
    - php Tests/Fixtures/bin/console --env=test assetic:dump

script:
    - vendor/bin/phpunit

after_script:
    - php Tests/Fixtures/bin/console --env=test doctrine:database:drop --force
